language: php

php:
  - 7.4

env:
  - TEST_TYPE="cover" STABILITY="--prefer-stable"
  - TEST_TYPE="style" STABILITY=""

before_install:
  - |
    if [ "$TEST_TYPE" = "style" ]; then
      phpenv config-rm xdebug.ini
    fi
  - composer self-update
  - |
    if [ "$TEST_TYPE" = "cover" ]; then
      composer require --dev --no-update php-coveralls/php-coveralls ^2.0
    fi
  - composer update $STABILITY

before_script:
  - |
    run_tests() {
      if [ "$TEST_TYPE" = "style" ]; then
        vendor/bin/phpcs --extensions=php --standard=phpcs.xml.dist src || travis_terminate 1
        vendor/bin/phpcs --extensions=php --standard=phpcs.xml.dist --ignore=*/CodeSamples/* tests || travis_terminate 1
        vendor/bin/php-cs-fixer --dry-run -v --config=cs-fixer.php.dist --path-mode=intersection fix src || travis_terminate 1
        vendor/bin/php-cs-fixer --dry-run -v --config=cs-fixer.php.dist --path-mode=intersection fix tests || travis_terminate 1
        vendor/bin/phpunit --exclude-group integrated
      else
        mkdir -p build/logs
        vendor/bin/phpunit --exclude-group integrated --coverage-clover build/logs/clover.xml
      fi
    }
script:
  - run_tests

after_success:
  - |
    if [ "$TEST_TYPE" = "cover" ]; then
      vendor/bin/php-coveralls
    fi
