language: php

php:
  - 7.4

env:
  - TEST_TYPE="cover" STABILITY="--prefer-stable"
  - TEST_TYPE="style" STABILITY=""

before_install:
  - if [ "$TEST_TYPE" = "style" ]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update

before_script:
  - |
    run_tests() {
      if [ "$TEST_TYPE" = "style" ]; then
        vendor/bin/phpcs --extensions=php --standard=phpcs.xml.dist src;
        vendor/bin/phpcs --extensions=php --standard=phpcs.xml.dist --ignore=*/CodeSamples/* tests;
        vendor/bin/php-cs-fixer --dry-run -v --config=cs-fixer.php.dist --path-mode=intersection fix src;
        vendor/bin/php-cs-fixer --dry-run -v --config=cs-fixer.php.dist --path-mode=intersection fix tests;

        vendor/bin/phpunit --no-coverage --exclude-group integrated;
      else
        mkdir -p build/logs;
        vendor/bin/phpunit --exclude-group integrated;
      fi;
    }
  - composer update $STABILITY
script:
  - run_tests

after_success:
  - if [ "$TEST_TYPE" = "cover" ]; then vendor/bin/php-coveralls; fi;
