#!/usr/bin/env php
<?php

/*
 * This file is part of Polymorphine/CodeStandards package.
 *
 * (c) Shudd3r <q3.shudder@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Polymorphine\CodeStandards;

function display($output) {
    foreach ($output as $line) {
        echo $line . PHP_EOL;
    }
}

function runCommand($command) {
    exec($command, $output, $exitCode);
    if ($exitCode) {
        display($output);
        exit($exitCode);
    }
}

unset($argv[0]);

$srcDir = empty($argv) ? 'src' : array_shift($argv);

$files = [];
if (!empty($argv)) {
    foreach ($argv as $file) {
        if (strpos($file, $srcDir) === 0) {
            $files[] = $file;
        }
    }
} else {
    $files[] = $srcDir;
}

runCommand('phpcs --extensions=php --standard=' . __DIR__ . '/phpcs.xml.dist ' . $srcDir);
if (!empty($files)) {
    $src = implode(' ', $files);
    runCommand('php-cs-fixer --dry-run -v --config=cs-fixer.php.dist --path-mode=intersection fix ' . $src);
}
